<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://soap.ws.bharath.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://trainings.ws.bharath.com/" name="CustomerOrdersWsImplService" targetNamespace="http://soap.ws.bharath.com/">
  <wsdl:import location="http://localhost:8080/wsdlfirstws/customerordersservice?wsdl=CustomerOrdersPortType.wsdl" namespace="http://trainings.ws.bharath.com/">
    </wsdl:import>
  <wsdl:binding name="CustomerOrdersWsImplServiceSoapBinding" type="ns1:CustomerOrdersPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="createOrders">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="createOrders">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="createOrdersResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getOrders">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getOrders">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getOrdersResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CustomerOrdersWsImplService">
    <wsdl:port binding="tns:CustomerOrdersWsImplServiceSoapBinding" name="CustomerOrdersWsImplPort">
      <soap:address location="http://localhost:8080/wsdlfirstws/customerordersservice"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>